name: Build and Push Docker Image

on:
  push:
    paths:
      - "Dockerfile" 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install

      - name: Build Docker Image
        run: |
          docker build -t bharat5/zomato-clone:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v3

        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push Docker Image
        run: docker push bharat5/zomato-clone:latest
